### PR TITLE
adding "make dev-shell" to enter development environment

### PR DESCRIPTION
**Pull request by benzaita**
The development environment can be configured using Docker. To drop into a shell with all the environment already set, just do:

```sh
# make dev-shell
```

You can then do `yarn start`, `yarn test` etc.

To cleanup the Docker container, do `make clean`.

### CODE REVIEW

**Comment by amitavihud** [comment]
Why do we need this?

**Comment by benzaita** [comment]
Helps to keep everyone aligned with the dev tools. Plus, setting up an
environment is a one liner. Both are important when handing off a project.

**Comment by amitavihud** [comment]
I think we should use npm scrips rather than a Makefile.
`yarn start` and `yarn clean` if it's really necessary

**Comment by benzaita** [comment]
Usually make is installed everywhere, and it's pretty stable, so there is
no confusion around which version of make to use. That is to say that "make
dev-shell" will usually work where "npm start" (or worse, "yarn start")
won't.
Additionally, it could be confusing to do "yarn start" once to enter into
the dev shell, and again to start the web server.

**Review by orgoldfus — APPROVED** [review]

**Comment by guyisra** [comment]
Maybe having it as 'make leket' instead if dev-shell?

**Review by guyisra — APPROVED** [review]

**Comment by benzaita** [comment]
@guyisra I believe `dev-shell` is more meaningful - as the command starts a shell you can develop in. But if you insist - I don't mind.

@amitavihud did I answer your question?

**Comment by guyisra** [comment]
@benzaita I don't care, just realized it will all be inside the leket folder anyway

**Pull request merged**
